### ISSUE TITLE
Build fails on 32-bit Linux

### ISSUE THREAD

**Issue by akkartik** [basic-gongfu/cixl#7]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

$ make
...
In file included from /home/akkartik/cixl/src/cixl/box.h:10:0,
                 from /home/akkartik/cixl/src/cixl/arg.h:6,
                 from /home/akkartik/cixl/src/cixl/lib/time.c:6:
/home/akkartik/cixl/src/cixl/lib/time.c: In function ‘days_imp’:
/home/akkartik/cixl/src/cixl/time.h:9:19: error: integer overflow in expression [-Werror=overflow]
 #define CX_MIN (60*CX_SEC)
                   ^
...
```

Looks like it's only been tested on 64-bit systems. So I made the following change:

```diff
--- a/src/cixl/time.h
+++ b/src/cixl/time.h
@@ -3,7 +3,7 @@

 #include <stdint.h>

-#define CX_USEC 1000L
+#define CX_USEC 1000LL
 #define CX_MSEC (1000*CX_USEC)
 #define CX_SEC (1000*CX_MSEC)
 #define CX_MIN (60*CX_SEC)
```

Now the build succeeds. However, the binary always segfaults.

```
$ ./cixl
zsh: segmentation fault  ./cixl
$ ./cixl -e ../examples/guess.cx -o guess
zsh: segmentation fault  ./cixl -e ../examples/guess.cx -o guess
$ gdb cixl
(gdb) r
Program received signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x0805cebe in cx_copy (dst=0x80a53a0, src=0xbfffebb4) at /home/akkartik/cixl/src/cixl/box.c:57
#1  0x08056fd0 in cx_error_init (e=0x80a5368, cx=0x80a1a40 <cx>, row=-1, col=-1, v=0xbfffebb4)
    at /home/akkartik/cixl/src/cixl/error.c:23
#2  0x08057201 in new_error (cx=0x80a1a40 <cx>, row=-1, col=-1, v=0xbfffebb4)
    at /home/akkartik/cixl/src/cixl/error.c:66
#3  0x08057409 in cx_error (cx=0x80a1a40 <cx>, row=-1, col=-1, spec=0x80806a4 "Lib not found: %s")
    at /home/akkartik/cixl/src/cixl/error.c:118
#4  0x0806189b in cx_vuse (cx=0x80a1a40 <cx>, lib_id=0x80805e3 "cx/io", nids=1, ids=0xbfffec80)
    at /home/akkartik/cixl/src/cixl/lib.c:514
#5  0x0804d766 in main (argc=1, argv=0xbfffed54) at /home/akkartik/cixl/src/main.c:29
(gdb) p src
$1 = (const struct cx_box *) 0xbfffebb4
(gdb) p src->type
$2 = (struct cx_type *) 0x0
```

**Comment by basic-gongfu** [comment]
That's correct, it's only been tested on 64-bit as far as I know.
Thanks for looking into it, I'll see if I can chase something down from the trace and get back to you.

**Comment by basic-gongfu** [comment]
Alright, sorry for the delay.
Would you mind pulling the latest changes and having another go? I've added ```LL``` and installed a signal handler to dump any thrown errors on segmentation faults, hopefully that gives us some more clues as to what's going on.

**Comment by akkartik** [comment]
Thanks for the update. I'm still seeing an issue on 32-bit Linux.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
$ uname -a
Linux akkartik 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:14 UTC 2018 i686 i686 i686 GNU/Linux
$ gdb cixl
Reading symbols from cixl...done.
(gdb) r
Program received signal SIGSEGV, Segmentation fault.
0x0805e61e in cx_copy (dst=0x80af170, src=0xbfffebcc) at /home/akkartik/cixl/src/cixl/box.c:57
57	  if (src->type->copy) {
(gdb) bt
#0  0x0805e61e in cx_copy (dst=0x80af170, src=0xbfffebcc) at /home/akkartik/cixl/src/cixl/box.c:57
#1  0x08057ac0 in cx_error_init (e=0x80af138, cx=0x80a8a60 <cx>, row=-1, col=-1, v=0xbfffebcc) at /home/akkartik/cixl/src/cixl/error.c:28
#2  0x08057dba in cx_error_new (v=0xbfffebcc, col=-1, row=-1, cx=0x80a8a60 <cx>) at /home/akkartik/cixl/src/cixl/error.c:18
#3  new_error (cx=0x80a8a60 <cx>, row=-1, col=-1, v=0xbfffebcc) at /home/akkartik/cixl/src/cixl/error.c:83
#4  0x08057e39 in cx_error (cx=0x80a8a60 <cx>, row=-1, col=-1, spec=0x8083752 "Lib not found: %s") at /home/akkartik/cixl/src/cixl/error.c:98
#5  0x08062b8b in cx_vuse (cx=0x80a8a60 <cx>, lib_id=0x8083691 "cx/io", nids=1, ids=0xbfffec90) at /home/akkartik/cixl/src/cixl/lib.c:521
#6  0x0804da7c in main (argc=1, argv=0xbfffed64) at /home/akkartik/cixl/src/main.c:49
(gdb) p src
$1 = (const struct cx_box *) 0xbfffebcc
(gdb) p src->type
$2 = (struct cx_type *) 0x0
```

I had to make one change to get it to compile:
```diff
diff --git a/src/cixl/lib/term.c b/src/cixl/lib/term.c
index 486027a..67b42a1 100644
--- a/src/cixl/lib/term.c
+++ b/src/cixl/lib/term.c
@@ -157,7 +157,7 @@ static bool move_up_imp(struct cx_call *call) {
     *n = cx_test(cx_call_arg(call, 0)),
     *out = cx_test(cx_call_arg(call, 1));

-  fprintf(cx_file_ptr(out->as_file), CX_CSI_ESC "%ldA", n->as_int);
+  fprintf(cx_file_ptr(out->as_file), CX_CSI_ESC "%lldA", n->as_int);
   return true;
 }

@@ -166,7 +166,7 @@ static bool move_down_imp(struct cx_call *call) {
     *n = cx_test(cx_call_arg(call, 0)),
     *out = cx_test(cx_call_arg(call, 1));

-  fprintf(cx_file_ptr(out->as_file), CX_CSI_ESC "%ldB", n->as_int);
+  fprintf(cx_file_ptr(out->as_file), CX_CSI_ESC "%lldB", n->as_int);
   return true;
 }

@@ -175,7 +175,7 @@ static bool move_left_imp(struct cx_call *call) {
     *n = cx_test(cx_call_arg(call, 0)),
     *out = cx_test(cx_call_arg(call, 1));

-  fprintf(cx_file_ptr(out->as_file), CX_CSI_ESC "%ldD", n->as_int);
+  fprintf(cx_file_ptr(out->as_file), CX_CSI_ESC "%lldD", n->as_int);
   return true;
 }

@@ -184,7 +184,7 @@ static bool move_right_imp(struct cx_call *call) {
     *n = cx_test(cx_call_arg(call, 0)),
     *out = cx_test(cx_call_arg(call, 1));

-  fprintf(cx_file_ptr(out->as_file), CX_CSI_ESC "%ldC", n->as_int);
+  fprintf(cx_file_ptr(out->as_file), CX_CSI_ESC "%lldC", n->as_int);
   return true;
 }

@@ -194,7 +194,7 @@ static bool move_to_imp(struct cx_call *call) {
     *y = cx_test(cx_call_arg(call, 1)),
     *out = cx_test(cx_call_arg(call, 2));

-  fprintf(cx_file_ptr(out->as_file), CX_CSI_ESC "%ld;%ldH", y->as_int, x->as_int);
+  fprintf(cx_file_ptr(out->as_file), CX_CSI_ESC "%lld;%lldH", y->as_int, x->as_int);
   return true;
 }
```

**Comment by basic-gongfu** [comment]
Right, thanks; I fixed the printf specifiers.

The error you're getting is because of a value with a NULL type, not a common issue since I didn't even check for it. I've now added a check when the value is constructed which will hopefully tell us more about where it's coming from. I would appreciate it if you could pull the latest changes and try once more.

**Comment by akkartik** [comment]
Sure thing. It built perfectly this time. The segfault now looks like this.

```
gdb cixl
Reading symbols from cixl...done.
(gdb) r
Starting program: /home/akkartik/cixl/build/cixl
'type' failed at line 12 in /home/akkartik/cixl/src/cixl/box.c

Program received signal SIGABRT, Aborted.
0xb7fdac31 in __kernel_vsyscall ()
(gdb) bt
#0  0xb7fdac31 in __kernel_vsyscall ()
#1  0xb7de1ea9 in __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#2  0xb7de3407 in __GI_abort () at abort.c:89
#3  0x0804db32 in cx_box_init (type=0x0, box=0xbfffe9d8) at /home/akkartik/cixl/src/cixl/box.c:12
#4  0x0805ea9a in cx_box_init (box=0xbfffe9d8, type=0x0) at /home/akkartik/cixl/src/cixl/box.c:14
#5  0x0805839c in cx_error (cx=0x80aba60 <cx>, row=-1, col=-1, spec=0x8085802 "Lib not found: %s")
    at /home/akkartik/cixl/src/cixl/error.c:95
#6  0x0806330b in cx_vuse (cx=0x80aba60 <cx>, lib_id=0x8085741 "cx/io", nids=1, ids=0xbfffeaa0)
    at /home/akkartik/cixl/src/cixl/lib.c:521
#7  0x0804dc6c in main (argc=1, argv=0xbfffeb74) at /home/akkartik/cixl/src/main.c:49
```

Let me know when you'd like me to try it again.
